name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '<%- nodeVersion %>'
    - name: Get package manager's global cache path
      id: global-cache-dir-path
      run: echo "::set-output name=dir::$(<%
        if (packageManager === 'npm') {
          %>npm config get cache<%
        } else {
          %>yarn cache dir<%
        } %>)"
    - name: Cache package manager's global cache
      id: cache-global-package-manager-cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.global-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
    - name: Install Dependencies
      run: <%
        if (packageManager === 'npm') {
          %>npm ci<%
        } else {
          %>yarn install --frozen-lockfile<%
        } %>
      if: |
        steps.cache-global-package-manager-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
    - name: Lint
      run: <% if (packageManager === 'npm') { %>npm run-script<% } else { %>yarn<% } %> lint

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [<%- browsers.join(', ') %>]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '<%- nodeVersion %>'
    - name: Get package manager's global cache path
      id: global-cache-dir-path
      run: echo "::set-output name=dir::$(<%
        if (packageManager === 'npm') {
          %>npm config get cache<%
        } else {
          %>yarn cache dir<%
        } %>)"
    - name: Cache package manager's global cache
      id: cache-global-package-manager-cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.global-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
    - name: Install Dependencies
      run: <%
        if (packageManager === 'npm') {
          %>npm ci<%
        } else {
          %>yarn install --frozen-lockfile<%
        } %>
      if: |
        steps.cache-global-package-manager-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
    - name: Test
      run: <% if (packageManager === 'npm') { %>npm run-script<% } else { %>yarn<% } %> test:ember --launch ${{ matrix.browser }}

  floating-dependencies:
    name: Floating Dependencies
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [<%- browsers.join(', ') %>]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '<%- nodeVersion %>'
    - name: Get package manager's global cache path
      id: global-cache-dir-path
      run: echo "::set-output name=dir::$(<%
        if (packageManager === 'npm') {
          %>npm config get cache<%
        } else {
          %>yarn cache dir<%
        } %>)"
    - name: Cache package manager's global cache
      id: cache-global-package-manager-cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.global-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
    - name: Install Dependencies
      run: <%
        if (packageManager === 'npm') {
          %>npm ci<%
        } else {
          %>yarn install --frozen-lockfile<%
        } %>
      if: |
        steps.cache-global-package-manager-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
    - name: Test
      run: <% if (packageManager === 'npm') { %>npm run-script<% } else { %>yarn<% } %> test:ember --launch ${{ matrix.browser }}

  try-scenarios:
    name: Tests - ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario: [<%
          emberTryScenarios.required.forEach(function(scenario, index){ %>
          <%- scenario %><% if (index < emberTryScenarios.required.length - 1) { %>,<% }}); %>
        ]
        allow-failure: [false]
        include:<%
          emberTryScenarios.allowedToFail.forEach(function(scenario){ %>
          - ember-try-scenario: <%- scenario %>
            allow-failure: true<% }); %>

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '<%- nodeVersion %>'
    - name: Get package manager's global cache path
      id: global-cache-dir-path
      run: echo "::set-output name=dir::$(<%
        if (packageManager === 'npm') {
          %>npm config get cache<%
        } else {
          %>yarn cache dir<%
        } %>)"
    - name: Cache package manager's global cache
      id: cache-global-package-manager-cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.global-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/<%
          if (packageManager === 'npm') {
            %>package-lock.json<%
          } else {
            %>yarn.lock<%
          } %>') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
    - name: Install Dependencies
      run: <%
        if (packageManager === 'npm') {
          %>npm ci<%
        } else {
          %>yarn install --frozen-lockfile<%
        } %>
      if: |
        steps.cache-global-package-manager-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
    - name: Test
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
